server:
  port: 8090
spring:
  application:
    name: scs
  jmx:
    enabled: false
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
  resources:
    static-locations: classpath:/static/

  datasource:
    #数据源基本配置
    #username: Zjf
    #password: zjf123456
    #url: jdbc:mysql://127.0.0.1:3306/chatbot?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: Zjf
    password: "@Zjf123456"
    url: jdbc:mysql://192.144.236.100:3306/chatbot?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai&connectTimeout=90000
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver


    #数据源其他配置
    maxActive: 20
    initialSize: 1
    maxWait: 600000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    maxPoolPreparedStatementPerConnectionSize: 500
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，’wall‘用于防火墙
    filters: stat，wall，log4j

  #热部署生效
  devtools:
    restart:
      enabled: true





